//! LLM-driven closet regeneration — richer topic extraction for the `compressed` table.
//!
//! Reads existing drawers and replaces each one's entry in the `compressed` table
//! with a topic-dense summary generated by a configured LLM. Regex compression
//! (from the `compress` command) is always the fallback; this path supplements it.
//!
//! Bring-your-own-LLM. Endpoint is any OpenAI-compatible Chat Completions URL.
//! Configure via env: `LLM_ENDPOINT`, `LLM_KEY`, `LLM_MODEL` or CLI flags.

use std::collections::HashSet;

use serde::Deserialize;
use turso::Connection;

use crate::db::query_all;
use crate::error::Result;
use crate::llm::client::LlmProvider;
use crate::palace::closets;

/// Maximum content characters sent to the LLM per drawer.
const MAX_CONTENT_CHARS: usize = 30_000;

/// Maximum topics retained from LLM response per drawer.
const MAX_TOPICS: usize = 15;

/// Maximum quotes retained from LLM response per drawer.
const MAX_QUOTES: usize = 5;

const _: () = assert!(MAX_CONTENT_CHARS > 0);
const _: () = assert!(MAX_TOPICS > 0);
const _: () = assert!(MAX_QUOTES > 0);

static SYSTEM_PROMPT: &str = "\
You are reading content filed in a memory palace. Generate a topic-dense index \
that will be used to find this content later when someone searches.

Output a JSON object with EXACTLY these fields:

{
  \"topics\": [\"distinctive_word_or_phrase_1\", \"topic_2\"],
  \"quotes\": [\"[Speaker] verbatim quote\"],
  \"summary\": \"2-3 sentences describing what this content is about.\"
}

RULES:
- Topics: 8-15 entries. Include proper nouns (names, places, projects), \
  distinctive technical terms, and key concepts. NOT generic words.
- Quotes: 2-5 entries. EXACT verbatim from the content. \
  Attribute with [Speaker] prefix if speaker is identifiable.
- Summary: mention WHO, WHAT, and WHY. No filler.
- Write in the same language as the content.
- Output valid JSON only. No code fences. No commentary.";

/// Statistics returned by [`regenerate_closets`].
#[derive(Debug, Default)]
pub struct RegenerateStats {
    /// Drawers successfully regenerated.
    pub processed: usize,
    /// Drawers skipped due to LLM failure.
    pub failed: usize,
    /// Drawers previewed in dry-run mode (not written).
    pub skipped_dry_run: usize,
}

/// Drawer row fetched from the database for regeneration.
struct DrawerRow {
    id: String,
    content: String,
    wing: String,
    room: String,
    source_file: String,
}

/// LLM JSON response shape.
#[derive(Deserialize, Default)]
struct ClosetOutput {
    #[serde(default)]
    topics: Vec<String>,
    #[serde(default)]
    quotes: Vec<String>,
    #[serde(default)]
    summary: String,
}

/// Regenerate `compressed` entries for drawers using a configured LLM.
///
/// Optionally filters to a single `wing`. When `sample > 0`, only the first
/// `sample` drawers are processed. In `dry_run` mode the LLM is NOT called and
/// nothing is written to the database; stats are returned with `skipped_dry_run`
/// incremented.
pub async fn regenerate_closets(
    connection: &Connection,
    wing: Option<&str>,
    sample: usize,
    dry_run: bool,
    provider: &dyn LlmProvider,
) -> Result<RegenerateStats> {
    assert!(
        sample < 1_000_001,
        "regenerate_closets: sample must be <= 1_000_000"
    );

    let drawers = regenerate_closets_fetch_drawers(connection, wing).await?;
    let limit = if sample > 0 {
        sample.min(drawers.len())
    } else {
        drawers.len()
    };

    // Purge stale closets before regenerating so that chunks deleted from the
    // drawers table do not leave orphaned entries in `compressed`.
    if !dry_run && !drawers.is_empty() {
        regenerate_closets_purge_sources(connection, &drawers[..limit]).await?;
    }

    let mut stats = RegenerateStats::default();
    for drawer in drawers.into_iter().take(limit) {
        if dry_run {
            stats.skipped_dry_run += 1;
            continue;
        }
        match regenerate_closets_process_drawer(connection, &drawer, provider).await {
            Ok(()) => stats.processed += 1,
            Err(_) => stats.failed += 1,
        }
    }

    assert!(
        stats.processed + stats.failed + stats.skipped_dry_run <= limit,
        "regenerate_closets: stat totals must not exceed limit"
    );

    Ok(stats)
}

/// Called by `regenerate_closets` to query drawers from the database.
///
/// When `wing` is `Some`, only drawers in that wing are returned.
/// Rows are ordered by `filed_at` ascending so processing is deterministic.
async fn regenerate_closets_fetch_drawers(
    connection: &Connection,
    wing: Option<&str>,
) -> Result<Vec<DrawerRow>> {
    let rows = if let Some(wing_filter) = wing {
        assert!(
            !wing_filter.is_empty(),
            "regenerate_closets_fetch_drawers: wing must not be empty"
        );
        query_all(
            connection,
            "SELECT id, content, wing, room, source_file FROM drawers WHERE wing = ? ORDER BY filed_at",
            (wing_filter,),
        )
        .await?
    } else {
        query_all(
            connection,
            "SELECT id, content, wing, room, source_file FROM drawers ORDER BY filed_at",
            (),
        )
        .await?
    };

    let mut drawers = Vec::with_capacity(rows.len());
    for row in &rows {
        let id: String = row.get(0).unwrap_or_default();
        let content: String = row.get(1).unwrap_or_default();
        let wing_val: String = row.get(2).unwrap_or_default();
        let room: String = row.get(3).unwrap_or_default();
        let source_file: String = row.get(4).unwrap_or_default();

        if id.is_empty() || content.is_empty() {
            continue;
        }
        drawers.push(DrawerRow {
            id,
            content,
            wing: wing_val,
            room,
            source_file,
        });
    }

    // Postcondition: every returned row has a non-empty id and content.
    debug_assert!(drawers.iter().all(|drawer| !drawer.id.is_empty()));
    debug_assert!(drawers.iter().all(|drawer| !drawer.content.is_empty()));

    Ok(drawers)
}

/// Called by `regenerate_closets` to purge stale closets before regenerating.
///
/// Collects unique non-empty source paths from `drawers` and calls
/// [`closets::purge_file_closets`] for each, so that chunks removed from the
/// `drawers` table do not leave orphaned entries in `compressed`.
async fn regenerate_closets_purge_sources(
    connection: &Connection,
    drawers: &[DrawerRow],
) -> Result<()> {
    assert!(
        !drawers.is_empty(),
        "regenerate_closets_purge_sources: drawers must not be empty"
    );

    let mut seen: HashSet<&str> = HashSet::new();
    for drawer in drawers {
        if drawer.source_file.is_empty() {
            continue;
        }
        if seen.insert(drawer.source_file.as_str()) {
            closets::purge_file_closets(connection, &drawer.source_file).await?;
        }
    }

    assert!(
        seen.len() <= drawers.len(),
        "regenerate_closets_purge_sources: unique source count must not exceed drawer count"
    );
    Ok(())
}

/// Called by `regenerate_closets` to process one drawer through the LLM and upsert the result.
///
/// Builds a user prompt from the drawer's metadata and content, calls the provider,
/// parses JSON, formats the output, and writes it to the `compressed` table.
async fn regenerate_closets_process_drawer(
    connection: &Connection,
    drawer: &DrawerRow,
    provider: &dyn LlmProvider,
) -> Result<()> {
    assert!(
        !drawer.id.is_empty(),
        "regenerate_closets_process_drawer: drawer id must not be empty"
    );
    assert!(
        !drawer.content.is_empty(),
        "regenerate_closets_process_drawer: content must not be empty"
    );

    let truncated = if drawer.content.len() > MAX_CONTENT_CHARS {
        let mut end = MAX_CONTENT_CHARS;
        while end > 0 && !drawer.content.is_char_boundary(end) {
            end -= 1;
        }
        &drawer.content[..end]
    } else {
        &drawer.content
    };

    let user_prompt = format!(
        "Source: {}\nWing: {} | Room: {}\n\nCONTENT:\n{truncated}",
        &drawer.source_file, &drawer.wing, &drawer.room,
    );

    let response = provider.classify(SYSTEM_PROMPT, &user_prompt, true)?;
    let output = regenerate_closets_parse_response(&response.text);
    let compressed = regenerate_closets_format_content(&output);

    if compressed.is_empty() {
        return Err(crate::error::Error::Other(format!(
            "LLM returned empty output for drawer {}",
            &drawer.id[..8.min(drawer.id.len())]
        )));
    }

    closets::upsert_closet_lines(connection, &drawer.id, &drawer.source_file, &compressed).await?;

    Ok(())
}

/// Called by `regenerate_closets_process_drawer` to parse the LLM JSON response.
///
/// Strips optional markdown code fences (` ```json `) before parsing.
/// Returns `ClosetOutput::default()` on any parse failure — the caller will
/// then produce an empty `compressed` string and count the drawer as failed.
fn regenerate_closets_parse_response(text: &str) -> ClosetOutput {
    assert!(
        !text.is_empty(),
        "regenerate_closets_parse_response: text must not be empty"
    );

    let cleaned = text
        .trim()
        .trim_start_matches("```json")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    serde_json::from_str(cleaned).unwrap_or_default()
}

/// Called by `regenerate_closets_process_drawer` to format `ClosetOutput` into stored text.
///
/// Produces pipe-joined topics on one line, one quote per line, and the summary.
/// Empty fields are omitted. The result is stored in `compressed.content`.
fn regenerate_closets_format_content(output: &ClosetOutput) -> String {
    let mut parts: Vec<String> = Vec::new();

    let topics: Vec<&str> = output
        .topics
        .iter()
        .take(MAX_TOPICS)
        .map(String::as_str)
        .collect();
    if !topics.is_empty() {
        parts.push(topics.join(" | "));
    }

    for quote in output.quotes.iter().take(MAX_QUOTES) {
        if !quote.is_empty() {
            parts.push(quote.clone());
        }
    }

    if !output.summary.is_empty() {
        parts.push(output.summary.clone());
    }

    let result = parts.join("\n");

    // Postcondition: non-empty output means at least one non-empty part was present.
    debug_assert!(result.is_empty() || !parts.is_empty());

    result
}

#[cfg(test)]
// Acceptable in tests: .expect() produces immediate, clear failures.
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    // Mock provider that always errors — used to verify dry_run never calls the LLM.
    struct FailProvider;
    impl LlmProvider for FailProvider {
        fn classify(
            &self,
            _system: &str,
            _user: &str,
            _json_mode: bool,
        ) -> crate::error::Result<crate::llm::client::LlmResponse> {
            Err(crate::error::Error::Other(
                "must not be called in dry_run".to_string(),
            ))
        }
        fn check_available(&self) -> (bool, String) {
            (false, "mock".to_string())
        }
        fn name(&self) -> &'static str {
            "mock"
        }
    }

    // ── regenerate_closets_parse_response ─────────────────────────────

    #[test]
    fn parse_response_valid_json() {
        let json = r#"{"topics": ["Rust", "memory"], "quotes": ["Alice said hi"], "summary": "About Rust."}"#;
        let output = regenerate_closets_parse_response(json);
        assert_eq!(output.topics.len(), 2);
        assert!(output.topics.contains(&"Rust".to_string()));
        assert_eq!(output.quotes.len(), 1);
        assert_eq!(output.summary, "About Rust.");
    }

    #[test]
    fn parse_response_strips_code_fence() {
        let json = "```json\n{\"topics\": [\"Rust\"], \"quotes\": [], \"summary\": \"S.\"}\n```";
        let output = regenerate_closets_parse_response(json);
        assert_eq!(output.topics, vec!["Rust"]);
        assert_eq!(output.summary, "S.");
    }

    #[test]
    fn parse_response_invalid_json_returns_default() {
        let output = regenerate_closets_parse_response("not json");
        assert!(output.topics.is_empty());
        assert!(output.summary.is_empty());
    }

    // ── regenerate_closets_format_content ────────────────────────────

    #[test]
    fn format_content_produces_pipe_joined_topics() {
        let output = ClosetOutput {
            topics: vec!["Rust".to_string(), "memory".to_string()],
            quotes: vec![],
            summary: String::new(),
        };
        let content = regenerate_closets_format_content(&output);
        assert!(
            content.contains("Rust | memory"),
            "topics must be pipe-joined"
        );
    }

    #[test]
    fn format_content_empty_output_returns_empty_string() {
        let output = ClosetOutput::default();
        let content = regenerate_closets_format_content(&output);
        assert!(content.is_empty(), "empty output must produce empty string");
    }

    #[test]
    fn format_content_includes_summary() {
        let output = ClosetOutput {
            topics: vec![],
            quotes: vec![],
            summary: "This is a summary.".to_string(),
        };
        let content = regenerate_closets_format_content(&output);
        assert!(
            content.contains("This is a summary."),
            "summary must appear in content"
        );
    }

    // ── regenerate_closets (integration) ─────────────────────────────

    #[tokio::test]
    async fn regenerate_closets_dry_run_skips_all_drawers() {
        // Dry-run must not write anything and must increment skipped_dry_run.
        let (_db, connection) = crate::test_helpers::test_db().await;

        // Seed one drawer.
        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, added_by) VALUES (?, ?, ?, ?, ?)",
                (
                    "d1",
                    "personal",
                    "notes",
                    "Alice said hello three times. Alice Alice.",
                    "test",
                ),
            )
            .await
            .expect("seed drawer should succeed");

        let stats = regenerate_closets(&connection, None, 0, true, &FailProvider)
            .await
            .expect("dry_run should succeed without LLM calls");

        assert_eq!(stats.processed, 0, "dry_run must not process any drawers");
        assert_eq!(stats.failed, 0, "dry_run must not fail any drawers");
        assert_eq!(
            stats.skipped_dry_run, 1,
            "dry_run must count skipped drawers"
        );
    }
}
