//! LLM-driven closet regeneration — richer topic extraction for the `compressed` table.
//!
//! Reads existing drawers and replaces each one's entry in the `compressed` table
//! with a topic-dense summary generated by a configured LLM. Regex compression
//! (from the `compress` command) is always the fallback; this path supplements it.
//!
//! Bring-your-own-LLM. Endpoint is any OpenAI-compatible Chat Completions URL.
//! Configure via env: `LLM_ENDPOINT`, `LLM_KEY`, `LLM_MODEL` or CLI flags.

use serde::Deserialize;
use turso::Connection;

use crate::db::query_all;
use crate::error::Result;
use crate::llm::client::LlmProvider;
use crate::palace::closets;

/// Maximum content characters sent to the LLM per drawer.
const MAX_CONTENT_CHARS: usize = 30_000;

/// Maximum topics retained from LLM response per drawer.
const MAX_TOPICS: usize = 15;

/// Maximum quotes retained from LLM response per drawer.
const MAX_QUOTES: usize = 5;

const _: () = assert!(MAX_CONTENT_CHARS > 0);
const _: () = assert!(MAX_TOPICS > 0);
const _: () = assert!(MAX_QUOTES > 0);

static SYSTEM_PROMPT: &str = "\
You are reading content filed in a memory palace. Generate a topic-dense index \
that will be used to find this content later when someone searches.

Output a JSON object with EXACTLY these fields:

{
  \"topics\": [\"distinctive_word_or_phrase_1\", \"topic_2\"],
  \"quotes\": [\"[Speaker] verbatim quote\"],
  \"summary\": \"2-3 sentences describing what this content is about.\"
}

RULES:
- Topics: 8-15 entries. Include proper nouns (names, places, projects), \
  distinctive technical terms, and key concepts. NOT generic words.
- Quotes: 2-5 entries. EXACT verbatim from the content. \
  Attribute with [Speaker] prefix if speaker is identifiable.
- Summary: mention WHO, WHAT, and WHY. No filler.
- Write in the same language as the content.
- Output valid JSON only. No code fences. No commentary.";

/// Statistics returned by [`regenerate_closets`].
#[derive(Debug, Default)]
pub struct RegenerateStats {
    /// Drawers successfully regenerated.
    pub processed: usize,
    /// Drawers skipped due to LLM failure.
    pub failed: usize,
    /// Drawers previewed in dry-run mode (not written).
    pub skipped_dry_run: usize,
}

/// Drawer row fetched from the database for regeneration.
struct DrawerRow {
    id: String,
    content: String,
    wing: String,
    room: String,
    source_file: String,
}

/// LLM JSON response shape.
#[derive(Deserialize, Default)]
struct ClosetOutput {
    #[serde(default)]
    topics: Vec<String>,
    #[serde(default)]
    quotes: Vec<String>,
    #[serde(default)]
    summary: String,
}

/// Regenerate `compressed` entries for drawers using a configured LLM.
///
/// Optionally filters to a single `wing`. When `sample > 0`, only the first
/// `sample` drawers are processed. In `dry_run` mode the LLM is NOT called and
/// nothing is written to the database; stats are returned with `skipped_dry_run`
/// incremented.
pub async fn regenerate_closets(
    connection: &Connection,
    wing: Option<&str>,
    sample: usize,
    dry_run: bool,
    provider: &dyn LlmProvider,
) -> Result<RegenerateStats> {
    assert!(
        sample < 1_000_001,
        "regenerate_closets: sample must be <= 1_000_000"
    );

    // Push the sample cap into SQL so we never materialize the entire drawers
    // table just to throw most rows away. `sample == 0` means "no cap".
    let sql_limit = if sample > 0 { Some(sample) } else { None };
    let drawers = regenerate_closets_fetch_drawers(connection, wing, sql_limit).await?;
    let limit = drawers.len();

    // Do not purge upfront: a provider failure mid-batch would otherwise wipe
    // existing closets the user could still rely on. Replacement happens
    // atomically per drawer inside upsert_closet_lines (INSERT OR REPLACE).

    let mut stats = RegenerateStats::default();
    for drawer in drawers {
        if dry_run {
            stats.skipped_dry_run += 1;
            continue;
        }
        match regenerate_closets_process_drawer(connection, &drawer, provider).await {
            Ok(()) => stats.processed += 1,
            Err(_) => stats.failed += 1,
        }
    }

    assert!(
        stats.processed + stats.failed + stats.skipped_dry_run <= limit,
        "regenerate_closets: stat totals must not exceed limit"
    );

    Ok(stats)
}

/// Called by `regenerate_closets` to query drawers from the database.
///
/// When `wing` is `Some`, only drawers in that wing are returned. When `limit`
/// is `Some(n)`, the SQL query caps the result set at `n` rows so the entire
/// table never has to be materialized client-side just to be truncated.
/// Rows are ordered by `(filed_at, id)` ascending so processing is deterministic
/// even when multiple drawers share the same `filed_at` timestamp.
async fn regenerate_closets_fetch_drawers(
    connection: &Connection,
    wing: Option<&str>,
    limit: Option<usize>,
) -> Result<Vec<DrawerRow>> {
    let rows = regenerate_closets_fetch_drawers_query(connection, wing, limit).await?;

    let mut drawers = Vec::with_capacity(rows.len());
    for row in &rows {
        let id: String = row.get(0).unwrap_or_default();
        let content: String = row.get(1).unwrap_or_default();
        let wing_val: String = row.get(2).unwrap_or_default();
        let room: String = row.get(3).unwrap_or_default();
        let source_file: String = row.get(4).unwrap_or_default();

        // Reject rows missing any field that would later break closet boost
        // grouping. An empty `source_file` would group every such row under
        // the empty-string key in `search_closet_boost`, collapsing distinct
        // drawers into a single bucket; better to skip them upstream than
        // to ever pass `""` to `upsert_closet_lines`.
        if id.is_empty() || content.is_empty() || source_file.is_empty() {
            continue;
        }
        drawers.push(DrawerRow {
            id,
            content,
            wing: wing_val,
            room,
            source_file,
        });
    }

    // Postcondition: every returned row has a non-empty id, content, and
    // `source_file` — the latter is the key used by `upsert_closet_lines`
    // and `search_closet_boost`, so an empty value would silently corrupt
    // boost lookup downstream.
    debug_assert!(drawers.iter().all(|drawer| !drawer.id.is_empty()));
    debug_assert!(drawers.iter().all(|drawer| !drawer.content.is_empty()));
    debug_assert!(drawers.iter().all(|drawer| !drawer.source_file.is_empty()));

    Ok(drawers)
}

/// Called by `regenerate_closets_fetch_drawers` to run the parameterized SELECT.
///
/// Split out so the parent stays under the 70-line cap; this leaf concentrates
/// the four-way `(wing?, limit?)` branching that turso requires because each
/// branch needs a distinct param tuple type.
async fn regenerate_closets_fetch_drawers_query(
    connection: &Connection,
    wing: Option<&str>,
    limit: Option<usize>,
) -> Result<Vec<turso::Row>> {
    // Bind LIMIT as i64 because turso's parameter binding is integer-typed and
    // SQLite's LIMIT clause expects a signed value. Clamp to i64::MAX so a
    // pathological `usize` from a 64-bit caller never wraps to a negative.
    let limit_i64: Option<i64> = limit.map(|count| i64::try_from(count).unwrap_or(i64::MAX));

    match (wing, limit_i64) {
        (Some(wing_filter), Some(limit_value)) => {
            assert!(
                !wing_filter.is_empty(),
                "regenerate_closets_fetch_drawers_query: wing must not be empty"
            );
            query_all(
                connection,
                "SELECT id, content, wing, room, source_file FROM drawers WHERE wing = ?1 ORDER BY filed_at, id LIMIT ?2",
                (wing_filter, limit_value),
            )
            .await
        }
        (Some(wing_filter), None) => {
            assert!(
                !wing_filter.is_empty(),
                "regenerate_closets_fetch_drawers_query: wing must not be empty"
            );
            query_all(
                connection,
                "SELECT id, content, wing, room, source_file FROM drawers WHERE wing = ? ORDER BY filed_at, id",
                (wing_filter,),
            )
            .await
        }
        (None, Some(limit_value)) => {
            query_all(
                connection,
                "SELECT id, content, wing, room, source_file FROM drawers ORDER BY filed_at, id LIMIT ?1",
                (limit_value,),
            )
            .await
        }
        (None, None) => {
            query_all(
                connection,
                "SELECT id, content, wing, room, source_file FROM drawers ORDER BY filed_at, id",
                (),
            )
            .await
        }
    }
}

/// Called by `regenerate_closets` to process one drawer through the LLM and upsert the result.
///
/// Builds a user prompt from the drawer's metadata and content, calls the provider,
/// parses JSON, formats the output, and writes it to the `compressed` table.
async fn regenerate_closets_process_drawer(
    connection: &Connection,
    drawer: &DrawerRow,
    provider: &dyn LlmProvider,
) -> Result<()> {
    assert!(
        !drawer.id.is_empty(),
        "regenerate_closets_process_drawer: drawer id must not be empty"
    );
    assert!(
        !drawer.content.is_empty(),
        "regenerate_closets_process_drawer: content must not be empty"
    );

    // Truncate to MAX_CONTENT_CHARS Unicode scalar values, not bytes — the
    // constant's name promises chars, and a 4-byte emoji must count as one
    // unit, not four. `char_indices().nth(n)` gives the byte offset of the
    // n-th char's start, falling back to the full length when the string is
    // shorter than the limit (in which case the slice is the whole string).
    let truncated_owned: String;
    let truncated: &str = if drawer.content.chars().count() > MAX_CONTENT_CHARS {
        let end = drawer
            .content
            .char_indices()
            .nth(MAX_CONTENT_CHARS)
            .map_or(drawer.content.len(), |(idx, _)| idx);
        truncated_owned = drawer.content[..end].to_string();
        &truncated_owned
    } else {
        &drawer.content
    };

    let user_prompt = format!(
        "Source: {}\nWing: {} | Room: {}\n\nCONTENT:\n{truncated}",
        &drawer.source_file, &drawer.wing, &drawer.room,
    );

    // Build a UTF-8-safe preview by chars, not bytes: drawer IDs are ASCII
    // today but a future schema change could carry multi-byte content, and a
    // byte slice in the middle of a code point would panic the whole batch.
    let id_preview: String = drawer.id.chars().take(8).collect();
    let response = provider.classify(SYSTEM_PROMPT, &user_prompt, true)?;
    if response.text.trim().is_empty() {
        return Err(crate::error::Error::Other(format!(
            "LLM returned empty response for drawer {id_preview}"
        )));
    }
    let output = regenerate_closets_parse_response(&response.text);
    let compressed = regenerate_closets_format_content(&output);

    if compressed.is_empty() {
        return Err(crate::error::Error::Other(format!(
            "LLM returned empty output for drawer {id_preview}"
        )));
    }

    closets::upsert_closet_lines(connection, &drawer.id, &drawer.source_file, &compressed).await?;

    Ok(())
}

/// Called by `regenerate_closets_process_drawer` to parse the LLM JSON response.
///
/// Strips optional markdown code fences (` ```json `) before parsing.
/// Returns `ClosetOutput::default()` on any parse failure — the caller will
/// then produce an empty `compressed` string and count the drawer as failed.
fn regenerate_closets_parse_response(text: &str) -> ClosetOutput {
    assert!(
        !text.is_empty(),
        "regenerate_closets_parse_response: text must not be empty"
    );

    let cleaned = text
        .trim()
        .trim_start_matches("```json")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    serde_json::from_str(cleaned).unwrap_or_default()
}

/// Called by `regenerate_closets_process_drawer` to format `ClosetOutput` into stored text.
///
/// Produces pipe-joined topics on one line, one quote per line, and the summary.
/// Empty fields are omitted. The result is stored in `compressed.content`.
fn regenerate_closets_format_content(output: &ClosetOutput) -> String {
    let mut parts: Vec<String> = Vec::new();

    let topics: Vec<&str> = output
        .topics
        .iter()
        .take(MAX_TOPICS)
        .map(String::as_str)
        .collect();
    if !topics.is_empty() {
        parts.push(topics.join(" | "));
    }

    for quote in output.quotes.iter().take(MAX_QUOTES) {
        if !quote.is_empty() {
            parts.push(quote.clone());
        }
    }

    if !output.summary.is_empty() {
        parts.push(output.summary.clone());
    }

    let result = parts.join("\n");

    // Postcondition: non-empty output means at least one non-empty part was present.
    debug_assert!(result.is_empty() || !parts.is_empty());

    result
}

#[cfg(test)]
// Acceptable in tests: .expect() produces immediate, clear failures.
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    // Mock provider that always errors — used to verify dry_run never calls the LLM.
    struct FailProvider;
    impl LlmProvider for FailProvider {
        fn classify(
            &self,
            _system: &str,
            _user: &str,
            _json_mode: bool,
        ) -> crate::error::Result<crate::llm::client::LlmResponse> {
            Err(crate::error::Error::Other(
                "must not be called in dry_run".to_string(),
            ))
        }
        fn check_available(&self) -> (bool, String) {
            (false, "mock".to_string())
        }
        fn name(&self) -> &'static str {
            "mock"
        }
    }

    // ── regenerate_closets_parse_response ─────────────────────────────

    #[test]
    fn parse_response_valid_json() {
        let json = r#"{"topics": ["Rust", "memory"], "quotes": ["Alice said hi"], "summary": "About Rust."}"#;
        let output = regenerate_closets_parse_response(json);
        assert_eq!(output.topics.len(), 2);
        assert!(output.topics.contains(&"Rust".to_string()));
        assert_eq!(output.quotes.len(), 1);
        assert_eq!(output.summary, "About Rust.");
    }

    #[test]
    fn parse_response_strips_code_fence() {
        let json = "```json\n{\"topics\": [\"Rust\"], \"quotes\": [], \"summary\": \"S.\"}\n```";
        let output = regenerate_closets_parse_response(json);
        assert_eq!(output.topics, vec!["Rust"]);
        assert_eq!(output.summary, "S.");
    }

    #[test]
    fn parse_response_invalid_json_returns_default() {
        let output = regenerate_closets_parse_response("not json");
        assert!(output.topics.is_empty());
        assert!(output.summary.is_empty());
    }

    // ── regenerate_closets_format_content ────────────────────────────

    #[test]
    fn format_content_produces_pipe_joined_topics() {
        let output = ClosetOutput {
            topics: vec!["Rust".to_string(), "memory".to_string()],
            quotes: vec![],
            summary: String::new(),
        };
        let content = regenerate_closets_format_content(&output);
        assert!(
            content.contains("Rust | memory"),
            "topics must be pipe-joined"
        );
    }

    #[test]
    fn format_content_empty_output_returns_empty_string() {
        let output = ClosetOutput::default();
        let content = regenerate_closets_format_content(&output);
        assert!(content.is_empty(), "empty output must produce empty string");
    }

    #[test]
    fn format_content_includes_summary() {
        let output = ClosetOutput {
            topics: vec![],
            quotes: vec![],
            summary: "This is a summary.".to_string(),
        };
        let content = regenerate_closets_format_content(&output);
        assert!(
            content.contains("This is a summary."),
            "summary must appear in content"
        );
    }

    // Mock provider that succeeds with a canned JSON response.
    struct OkProvider;
    impl LlmProvider for OkProvider {
        fn classify(
            &self,
            _system: &str,
            _user: &str,
            _json_mode: bool,
        ) -> crate::error::Result<crate::llm::client::LlmResponse> {
            Ok(crate::llm::client::LlmResponse {
                text: r#"{"topics":["Rust","memory","palace"],"quotes":["Alice said hi"],"summary":"A test summary."}"#
                    .to_string(),
            })
        }
        fn check_available(&self) -> (bool, String) {
            (true, "ok".to_string())
        }
        fn name(&self) -> &'static str {
            "mock-ok"
        }
    }

    // Mock provider that returns an empty string — triggers the empty-response error path.
    struct EmptyResponseProvider;
    impl LlmProvider for EmptyResponseProvider {
        fn classify(
            &self,
            _system: &str,
            _user: &str,
            _json_mode: bool,
        ) -> crate::error::Result<crate::llm::client::LlmResponse> {
            Ok(crate::llm::client::LlmResponse {
                text: "   ".to_string(),
            })
        }
        fn check_available(&self) -> (bool, String) {
            (true, "ok".to_string())
        }
        fn name(&self) -> &'static str {
            "mock-empty"
        }
    }

    // ── regenerate_closets_parse_response — additional paths ─────────

    #[test]
    fn parse_response_strips_bare_backtick_fence() {
        // A ``` fence without "json" label must also be stripped before parsing.
        let json = "```\n{\"topics\": [\"Rust\"], \"quotes\": [], \"summary\": \"Bare.\"}\n```";
        let output = regenerate_closets_parse_response(json);
        assert_eq!(
            output.topics,
            vec!["Rust"],
            "topics must parse through bare fence"
        );
        assert_eq!(
            output.summary, "Bare.",
            "summary must parse through bare fence"
        );
    }

    // ── regenerate_closets_format_content — additional paths ─────────

    #[test]
    fn format_content_includes_quotes() {
        // Non-empty quotes must appear as separate lines between topics and summary.
        let output = ClosetOutput {
            topics: vec!["Rust".to_string()],
            quotes: vec!["[Alice] verbatim quote".to_string()],
            summary: "About Rust.".to_string(),
        };
        let content = regenerate_closets_format_content(&output);
        assert!(
            content.contains("[Alice] verbatim quote"),
            "non-empty quotes must appear in output"
        );
        assert!(
            content.contains("About Rust."),
            "summary must appear alongside quotes"
        );
    }

    #[test]
    fn format_content_truncates_topics_to_max() {
        // When more than MAX_TOPICS topics are provided only the first MAX_TOPICS appear.
        let topics: Vec<String> = (0..=MAX_TOPICS).map(|i| format!("topic_{i}")).collect();
        let output = ClosetOutput {
            topics,
            quotes: vec![],
            summary: String::new(),
        };
        let content = regenerate_closets_format_content(&output);
        // The MAX_TOPICS+1-th topic must not appear (0-indexed: topic_15 for MAX_TOPICS=15).
        assert!(
            !content.contains(&format!("topic_{MAX_TOPICS}")),
            "topics must be truncated to MAX_TOPICS"
        );
        assert!(
            content.contains("topic_0"),
            "first topic must appear in truncated output"
        );
    }

    #[test]
    fn format_content_skips_empty_quotes() {
        // An empty string in the quotes Vec must not add a blank line to output.
        let output = ClosetOutput {
            topics: vec![],
            quotes: vec![String::new(), "real quote".to_string()],
            summary: String::new(),
        };
        let content = regenerate_closets_format_content(&output);
        assert!(
            content.contains("real quote"),
            "non-empty quote must appear"
        );
        // The content should not start with a newline (blank line from empty quote).
        assert!(
            !content.starts_with('\n'),
            "empty quotes must not add blank lines"
        );
    }

    // ── regenerate_closets (integration) ─────────────────────────────

    #[tokio::test]
    async fn regenerate_closets_dry_run_skips_all_drawers() {
        // Dry-run must not write anything and must increment skipped_dry_run.
        let (_db, connection) = crate::test_helpers::test_db().await;

        // Seed one drawer. `source_file` must be non-empty for the fetch to
        // include the row (an empty source_file would collapse closet boost
        // grouping in production and is filtered out at the fetch stage).
        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    "d1",
                    "personal",
                    "notes",
                    "Alice said hello three times. Alice Alice.",
                    "alice.md",
                    "test",
                ),
            )
            .await
            .expect("seed drawer should succeed");

        let stats = regenerate_closets(&connection, None, 0, true, &FailProvider)
            .await
            .expect("dry_run should succeed without LLM calls");

        assert_eq!(stats.processed, 0, "dry_run must not process any drawers");
        assert_eq!(stats.failed, 0, "dry_run must not fail any drawers");
        assert_eq!(
            stats.skipped_dry_run, 1,
            "dry_run must count skipped drawers"
        );
    }

    #[tokio::test]
    async fn regenerate_closets_empty_palace_returns_zero_stats() {
        // When the palace has no drawers, all stats must be zero.
        let (_db, connection) = crate::test_helpers::test_db().await;

        let stats = regenerate_closets(&connection, None, 0, false, &OkProvider)
            .await
            .expect("regenerate_closets must succeed on empty palace");

        assert_eq!(stats.processed, 0, "empty palace must have zero processed");
        assert_eq!(stats.failed, 0, "empty palace must have zero failed");
        assert_eq!(
            stats.skipped_dry_run, 0,
            "empty palace must have zero skipped"
        );
    }

    #[tokio::test]
    async fn regenerate_closets_processes_drawer_with_ok_provider() {
        // A successful LLM call must increment processed and write a compressed row.
        let (_db, connection) = crate::test_helpers::test_db().await;

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_ok_1", "personal", "notes", "Alice said hello about Rust and memory.", "notes.md", "test"),
            )
            .await
            .expect("seed drawer must succeed");

        let stats = regenerate_closets(&connection, None, 0, false, &OkProvider)
            .await
            .expect("regenerate_closets must succeed");

        assert_eq!(stats.processed, 1, "one drawer must be processed");
        assert_eq!(stats.failed, 0, "no drawer must fail with OkProvider");

        // Pair assertion: the compressed table must have an entry for this drawer.
        let rows = crate::db::query_all(
            &connection,
            "SELECT id FROM compressed WHERE id = 'd_ok_1'",
            (),
        )
        .await
        .expect("select compressed must succeed");
        assert_eq!(
            rows.len(),
            1,
            "compressed entry must exist after processing"
        );
    }

    #[tokio::test]
    async fn regenerate_closets_counts_failed_when_provider_returns_empty() {
        // When the provider returns whitespace, the drawer counts as failed (not processed).
        let (_db, connection) = crate::test_helpers::test_db().await;

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_fail_1", "personal", "notes", "Content that will get an empty LLM reply.", "fail.md", "test"),
            )
            .await
            .expect("seed drawer must succeed");

        let stats = regenerate_closets(&connection, None, 0, false, &EmptyResponseProvider)
            .await
            .expect("regenerate_closets must not propagate LLM failure");

        assert_eq!(stats.failed, 1, "empty LLM response must count as failed");
        assert_eq!(
            stats.processed, 0,
            "no drawer must be processed on empty response"
        );
    }

    #[tokio::test]
    async fn regenerate_closets_sample_limits_processing() {
        // When sample=1, only one drawer is processed even if two exist.
        let (_db, connection) = crate::test_helpers::test_db().await;

        for (id, content) in [
            ("d_sample_1", "First drawer content about Rust."),
            ("d_sample_2", "Second drawer content about memory."),
        ] {
            connection
                .execute(
                    "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                    (id, "personal", "notes", content, "multi.md", "test"),
                )
                .await
                .expect("seed drawer must succeed");
        }

        let stats = regenerate_closets(&connection, None, 1, false, &OkProvider)
            .await
            .expect("regenerate_closets with sample=1 must succeed");

        assert_eq!(
            stats.processed + stats.failed,
            1,
            "sample=1 must limit to one drawer"
        );
        assert_eq!(
            stats.skipped_dry_run, 0,
            "not a dry_run so skipped must be zero"
        );
    }

    // Mock provider that returns content that serializes to non-empty JSON but
    // formats to an empty compressed string (empty topics, empty quotes, empty summary).
    struct EmptyOutputProvider;
    impl LlmProvider for EmptyOutputProvider {
        fn classify(
            &self,
            _system: &str,
            _user: &str,
            _json_mode: bool,
        ) -> crate::error::Result<crate::llm::client::LlmResponse> {
            // Valid JSON with all-empty fields — format_content will return "".
            Ok(crate::llm::client::LlmResponse {
                text: r#"{"topics":[],"quotes":[],"summary":""}"#.to_string(),
            })
        }
        fn check_available(&self) -> (bool, String) {
            (true, "ok".to_string())
        }
        fn name(&self) -> &'static str {
            "mock-empty-output"
        }
    }

    // ── regenerate_closets_fetch_drawers: skip rows with empty id or content ───

    #[tokio::test]
    async fn regenerate_closets_skips_drawer_with_empty_content() {
        // A database row with empty content must be skipped by the fetch function,
        // so the drawer is not passed to the LLM. Covers the `continue` on L171.
        let (_db, connection) = crate::test_helpers::test_db().await;

        // Insert a drawer with non-empty id but empty content (content = whitespace only
        // normalizes to empty at the app layer; use a truly empty string via raw SQL).
        // `source_file` is set so the fetch-stage source_file filter does not also
        // exclude the row — we want to verify the empty-content path specifically.
        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_empty_content", "test", "notes", "", "empty.md", "test"),
            )
            .await
            .expect("seed drawer with empty content must succeed");

        // Also insert a normal drawer so we can distinguish "skipped" from "none".
        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    "d_normal",
                    "test",
                    "notes",
                    "Normal content here.",
                    "normal.md",
                    "test",
                ),
            )
            .await
            .expect("seed normal drawer must succeed");

        // dry_run=true so the FailProvider is never called; we just count skipped_dry_run.
        let stats = regenerate_closets(&connection, None, 0, true, &FailProvider)
            .await
            .expect("regenerate_closets must succeed");

        // Only the one valid drawer must be counted; the empty-content one is skipped.
        assert_eq!(
            stats.skipped_dry_run, 1,
            "only one drawer (non-empty content) must be counted"
        );
    }

    #[tokio::test]
    async fn regenerate_closets_skips_drawer_with_empty_source_file() {
        // A drawer with empty source_file would collapse closet-boost grouping
        // (every empty-source row falls into the same boost bucket) and must be
        // filtered out at the fetch stage so it never reaches
        // upsert_closet_lines. Pair this with a normal row so we can distinguish
        // "filtered" from "none".
        let (_db, connection) = crate::test_helpers::test_db().await;

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_no_source", "test", "notes", "Has content but no source.", "", "test"),
            )
            .await
            .expect("seed drawer with empty source_file must succeed");

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    "d_with_source",
                    "test",
                    "notes",
                    "Has content and source.",
                    "with.md",
                    "test",
                ),
            )
            .await
            .expect("seed drawer with source_file must succeed");

        let stats = regenerate_closets(&connection, None, 0, true, &FailProvider)
            .await
            .expect("regenerate_closets must succeed");

        assert_eq!(
            stats.skipped_dry_run, 1,
            "only the row with a non-empty source_file must be processed"
        );
    }

    // ── regenerate_closets_process_drawer: empty compressed output counts as failed ──

    #[tokio::test]
    async fn regenerate_closets_counts_failed_when_format_produces_empty_string() {
        // When LLM returns valid JSON but all fields are empty, format_content returns ""
        // and the drawer must count as failed. Covers L258-261.
        let (_db, connection) = crate::test_helpers::test_db().await;

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_empty_fmt", "test", "notes", "Content here.", "empty.md", "test"),
            )
            .await
            .expect("seed drawer must succeed");

        let stats = regenerate_closets(&connection, None, 0, false, &EmptyOutputProvider)
            .await
            .expect("regenerate_closets must not propagate the failure");

        assert_eq!(
            stats.failed, 1,
            "empty formatted output must count as failed"
        );
        assert_eq!(
            stats.processed, 0,
            "drawer must not be counted as processed"
        );
    }

    // ── regenerate_closets_process_drawer: content truncation at UTF-8 boundary ──

    #[tokio::test]
    async fn regenerate_closets_truncates_multibyte_content_without_panic() {
        // Content with multi-byte chars (emoji) that exceeds MAX_CONTENT_CHARS
        // (counted in chars, not bytes) must be sliced at a valid char
        // boundary. Use one more emoji than the char cap so the truncation
        // path fires under the char-based logic.
        let (_db, connection) = crate::test_helpers::test_db().await;

        let emoji_count = MAX_CONTENT_CHARS + 5;
        let long_content = "🚀".repeat(emoji_count);
        assert!(
            long_content.chars().count() > MAX_CONTENT_CHARS,
            "test setup: content must exceed MAX_CONTENT_CHARS chars"
        );
        assert!(
            long_content.len() > MAX_CONTENT_CHARS,
            "test setup: content must also exceed MAX_CONTENT_CHARS bytes for the boundary walk"
        );

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_multibyte", "test", "notes", long_content.as_str(), "emoji.md", "test"),
            )
            .await
            .expect("seed multibyte drawer must succeed");

        // OkProvider always returns a valid response; the drawer must be processed.
        let stats = regenerate_closets(&connection, None, 0, false, &OkProvider)
            .await
            .expect("regenerate_closets must handle multibyte truncation without panic");

        assert_eq!(
            stats.processed, 1,
            "multibyte content must be processed without panic"
        );
        assert_eq!(
            stats.failed, 0,
            "no failure must occur for multibyte content"
        );
    }

    #[tokio::test]
    async fn regenerate_closets_wing_filter_only_processes_matching_wing() {
        // When wing is Some, only drawers from that wing are fetched.
        let (_db, connection) = crate::test_helpers::test_db().await;

        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_wing_match", "work", "projects", "Work drawer content about systems.", "work.md", "test"),
            )
            .await
            .expect("seed work drawer");
        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_wing_other", "personal", "notes", "Personal drawer content about life.", "personal.md", "test"),
            )
            .await
            .expect("seed personal drawer");

        // Process only the "work" wing in dry_run to count without writing.
        let stats = regenerate_closets(&connection, Some("work"), 0, true, &FailProvider)
            .await
            .expect("wing-filtered dry_run must succeed");

        assert_eq!(
            stats.skipped_dry_run, 1,
            "only one drawer in 'work' wing must be skipped"
        );
        assert_eq!(stats.processed, 0, "dry_run must not process anything");
    }

    #[tokio::test]
    async fn regenerate_closets_content_truncation_does_not_panic() {
        // A drawer whose content exceeds MAX_CONTENT_CHARS must be processed without panic.
        // The OkProvider always succeeds regardless of input size, so processed=1.
        let (_db, connection) = crate::test_helpers::test_db().await;

        // Build a string slightly larger than MAX_CONTENT_CHARS using ASCII chars only
        // so no multi-byte boundary issues arise in this test.
        let long_content = "a".repeat(MAX_CONTENT_CHARS + 100);
        connection
            .execute(
                "INSERT INTO drawers (id, wing, room, content, source_file, added_by) VALUES (?, ?, ?, ?, ?, ?)",
                ("d_long_content", "personal", "notes", long_content.as_str(), "long.md", "test"),
            )
            .await
            .expect("seed long drawer must succeed");

        let stats = regenerate_closets(&connection, None, 0, false, &OkProvider)
            .await
            .expect("regenerate_closets must handle long content without panic");

        assert_eq!(
            stats.processed, 1,
            "long content drawer must be processed successfully"
        );
        assert_eq!(stats.failed, 0, "long content must not trigger a failure");
    }
}
