name: Deny

on:
  workflow_call:

permissions: {}

jobs:
  run:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        env:
          MISE_JOBS: 4
        with:
          cache_key_prefix: mise-deny
          cache: true
          experimental: true
          install: true

      - run: mise x cargo:cargo-deny -- cargo deny check bans sources
